# Generated by Django 3.0.8 on 2020-10-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
