# Generated by Django 3.0.8 on 2020-10-08 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_promocode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
