# Generated by Django 3.0.8 on 2020-10-15 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0049_auto_20201009_2335'),
        ('orders', '0009_orderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='products',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='products',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
