# Generated by Django 2.2 on 2020-03-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20200306_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('m', 'medium'), ('l', 'large'), ('s', 'small')], max_length=2),
        ),
    ]
