# Generated by Django 2.2 on 2020-03-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20200306_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('m', 'medium'), ('s', 'small'), ('l', 'large')], max_length=2),
        ),
    ]
