# Generated by Django 2.2 on 2020-03-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200306_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('l', 'large'), ('s', 'small'), ('m', 'medium')], max_length=2),
        ),
    ]
