# Generated by Django 2.2 on 2020-03-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200306_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('l', 'large'), ('m', 'medium'), ('s', 'small')], max_length=2),
        ),
    ]
