# Generated by Django 2.2 on 2020-03-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200307_0746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('l', 'large'), ('s', 'small'), ('m', 'medium')], max_length=2),
        ),
    ]
