# Generated by Django 2.2 on 2020-03-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_auto_20200307_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('s', 'small'), ('l', 'large'), ('m', 'medium')], max_length=2),
        ),
    ]
