# Generated by Django 3.0.8 on 2020-10-06 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0041_auto_20201005_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='size',
            field=models.CharField(choices=[('l', 'large'), ('s', 'small'), ('m', 'medium')], max_length=2),
        ),
    ]
