# Generated by Django 3.0.8 on 2020-10-06 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0042_auto_20201006_0638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='size',
        ),
    ]
