# Generated by Django 3.0.8 on 2020-10-07 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0046_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
